user:
    path:     /
    defaults: { _controller: "UserBundle:User:index" }

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:User:delete" }
    requirements:
        id:  \d+

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:User:edit" }
    requirements:
        id:  \d+