documents:
    path:     /
    defaults: { _controller: "GedBundle:Documents:index" }

documents_show:
    path:     /{id}/show
    defaults: { _controller: "GedBundle:Documents:show" }



document_download:
    path:     /download/{document}
    defaults: { _controller: "GedBundle:Documents:Download" }

document_visual:
    path:     /visual/{document}
    defaults: { _controller: "GedBundle:Documents:Visual" }
