homepage:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }

agenda:
    resource: "@AgendaBundle/Resources/config/routing.yml"
    prefix:   /agenda

ged_documents:
    resource: "@GedBundle/Resources/config/routing/documents.yml"
    prefix:   /documents

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
