user_get_picture:
    path: /picture/{picture}
    defaults: { _controller: "UserBundle:PictureProfile:PictureProfile" }
    methods: [GET]

create_password:
    path: /create/password/{email}
    defaults: { _controller: "UserBundle:Registration:createPassword" }
    methods: [GET]