UserBundle\Entity\User:
    properties:
        email:
            - Email:
                message: L'email "{{ value }}" n'est pas un email valide.
                checkMX: true
        prenom:
            - NotBlank: ~
            - Length:
                max: 50
                maxMessage: "Le prenom ne peut contenir plus de 50 caractères"
            - Type:
                type: string
                message: "Ce champ ne peut contenir que des caractères alphabétique"
        nom:
            - NotBlank: ~
            - Length:
                max: 50
                maxMessage: "Le nom ne peut contenir plus de 50 caractères"
            - Type:
                type: string
                message: "Ce champ ne peut contenir que des caractères alphabétique"
        file:
            - File:
                maxSize: 20M
                mimeTypes: [application/pdf, application/x-pdf]
                mimeTypesMessage: "Merci d'uploader un document pdf valid"
