events:
    path:     /
    defaults: { _controller: "AgendaBundle:Events:index" }
    options:
        expose: true

events_show:
    path:     /{id}/show
    defaults: { _controller: "AgendaBundle:Events:show" }

events_new:
    path:     /{start}/new
    defaults: { _controller: "AgendaBundle:Events:new" }

events_create:
    path:     /create
    defaults: { _controller: "AgendaBundle:Events:create" }
    methods:  POST

events_edit:
    path:     /{id}/edit
    defaults: { _controller: "AgendaBundle:Events:edit" }

events_update:
    path:     /{id}/update
    defaults: { _controller: "AgendaBundle:Events:update" }
    methods:  [POST, PUT]

events_delete:
    path:     /{id}/delete
    defaults: { _controller: "AgendaBundle:Events:delete" }
    methods:  [POST, DELETE]