GedBundle\Entity\Documents:
    type: entity
    table: documents
    indexes:
        id_user:
            columns:
                - id_user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        resume:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        extension:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        auteur:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        url:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        dateUpload:
            type: datetime
            nullable: false
            column: date_upload
        dateModif:
            type: datetime
            nullable: false
            column: date_modif
        dureeDeVie:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: duree_de_vie
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_user
    lifecycleCallbacks: {  }
